### ISSUE TITLE
API Package installation errror

### ISSUE THREAD

**Issue by simille83** [chomupashchuk/ariston-remotethermo-home-assistant-v2#1]
Hi,

I tried to install the API package with the command "pip install aristonremotethermo" but I have a syntax error.
![Annotazione 2020-07-25 151927](https://user-images.githubusercontent.com/67116254/88457975-c4283700-ce8a-11ea-870a-d5bd1195b26a.jpg)
This is the error.

Thanks.
Simone

**Comment by chomupashchuk** [comment]
Hi,

This is my first package, so maybe there is some bug, but I have successfully uninstalled and installed in on my PC within Pycharm project and also in dev container for Home Assistant:
```
root@adce78bc8797:/workspaces/core-1# pip uninstall  aristonremotethermo
Found existing installation: aristonremotethermo 1.0.17
Uninstalling aristonremotethermo-1.0.17:
  Would remove:
    /usr/local/lib/python3.8/site-packages/aristonremotethermo-1.0.17.dist-info/*
    /usr/local/lib/python3.8/site-packages/aristonremotethermo/*
Proceed (y/n)? y
  Successfully uninstalled aristonremotethermo-1.0.17
root@adce78bc8797:/workspaces/core-1# pip install aristonremotethermo
Collecting aristonremotethermo
  Using cached aristonremotethermo-1.0.17-py3-none-any.whl (38 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (from aristonremotethermo) (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (1.25.9)
Installing collected packages: aristonremotethermo
Successfully installed aristonremotethermo-1.0.17
root@adce78bc8797:/workspaces/core-1# 
```

**Comment by chomupashchuk** [comment]
please note that pip install only installs class for management of the boiler, custom_component includes one of two files from pypi and other files required for the integration.

**Comment by simille83** [comment]
> Ciao
> 
> Questo è il mio primo pacchetto, quindi forse c'è qualche bug, ma ho disinstallato e installato con successo nel mio PC all'interno del progetto Pycharm e anche nel contenitore di sviluppo per Home Assistant:
> 
> ```
> root@adce78bc8797:/workspaces/core-1# pip uninstall  aristonremotethermo
> Found existing installation: aristonremotethermo 1.0.17
> Uninstalling aristonremotethermo-1.0.17:
>   Would remove:
>     /usr/local/lib/python3.8/site-packages/aristonremotethermo-1.0.17.dist-info/*
>     /usr/local/lib/python3.8/site-packages/aristonremotethermo/*
> Proceed (y/n)? y
>   Successfully uninstalled aristonremotethermo-1.0.17
> root@adce78bc8797:/workspaces/core-1# pip install aristonremotethermo
> Collecting aristonremotethermo
>   Using cached aristonremotethermo-1.0.17-py3-none-any.whl (38 kB)
> Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (from aristonremotethermo) (2.24.0)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (3.0.4)
> Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (2.10)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (2020.6.20)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests->aristonremotethermo) (1.25.9)
> Installing collected packages: aristonremotethermo
> Successfully installed aristonremotethermo-1.0.17
> root@adce78bc8797:/workspaces/core-1# 
> ```

I have Home Assistant Core on Raspbian in Venv, maybe I have to install it in the virtual environment?

**Comment by chomupashchuk** [comment]
I found following for the mentioned exception:
https://stackoverflow.com/questions/8548030/why-does-pip-install-inside-python-raise-a-syntaxerror

Pypi package (via pip install) should install latest "api" (2 python files ariston.py (for Ariston NET) and aristonaqua.py (for Aqua Ariston NET)). Api is responsible for the actual communication with a boiler. 
Custom component on the other hand includes the same ariston.py with other files, which are used as layer between api and Home Assistant to integrate it (aristonaqua.py is within another custom component). Intention was to have api somewhat outside of Home Assistant responsibility. Also api can be integrated in any python environment for different purposes (for example use it in appdaemon).

I would like to clarify: what exactly would you like to achieve? Do you use Raspdian OS with docker or Hassio OS?
As i understand HA core is a docker container, so if to use pip install and have api imported, it should probably be within docker container itself. But what would you like to do with it?

**Comment by simille83** [comment]
> Ho trovato di seguito
> per l'eccezione menzionata: https://stackoverflow.com/questions/8548030/why-does-pip-install-inside-python-raise-a-syntaxerror
> 
> Il pacchetto Pypi (tramite pip install) dovrebbe installare "api" più recente (2 file pitone ariston.py (per Ariston NET) e aristonaqua.py (per Aqua Ariston NET)). Api è responsabile della comunicazione effettiva con una caldaia.
> Il componente personalizzato include le stesse ariston.py con altri file, che vengono utilizzati come livello tra api e Home Assistant per integrarlo (aristonaqua.py si trova all'interno di un altro componente personalizzato). Intenzione era quello di avere api un po 'al di fuori della responsabilità Home Assistant. Anche api può essere integrato in qualsiasi ambiente python per scopi diversi (ad esempio usarlo in appdaemon).
> 
> Vorrei chiarire: cosa vorresti ottenere esattamente? Si utilizza Raspdian OS con docker o Hassio OS?
> Come ho capito core HA è un contenitore docker, quindi se per utilizzare pip install e hanno api importato, probabilmente dovrebbe essere all'interno del contenitore docker stesso. Ma cosa vorresti farne?

I have install again the integration by copying Ariston directory in custom components and now works.
I would just like to manage the boiler and solar storage via HA, so installing the API package is not necessary I can do without it. For now it's okay.
What does aristonaqua.py (for Aqua Ariston NET) consist of? Can i use it?
Is it possible to also have the heating system pressure sensor which is also present in the Ariston Net application?

Thanks.

**Comment by chomupashchuk** [comment]
For the Home Assistant use there is no need for pip install as you mentioned.

As for other file (aristonaqua.py): Ariston boilers support only one application: 
1) Ariston NET for boilers like Nimbus Flex, Genus One, Clas Evo etc.
2) Aqua Ariston NET for Lydos Wifi, Velis Wifi etc.
If you try to use not supported application for your boiler you would simply get no data after login.

As for the pressure sensor:
1.) Is pressure sensor available on https://www.ariston-net.remotethermo.com? If yes, then proceed with 2nd step. If not, then 3rd step would be required (simply integration emulates communication with that site)
2.) please use "store_files: True" within configuration.yaml under "ariston" and restart Home Assistant. It is used to store what kind of data is being reported by the boiler in "config/ariston_http_data" (in case of exception you might need to manually create the folder). If no luck, then 3rd step would be required.
3.) analyzer (fiddler is the easy to use) would have to be connected to the application towards your boiler (as i said mine does not have such an option) to see how data is being read. For this step to work either you would have to do it yourself or would have to provide me with login and password (surely not openly here).
