### ISSUE TITLE
Configure CH water temperature

### ISSUE THREAD

**Issue by HassioAwi** [chomupashchuk/ariston-remotethermo-home-assistant-v2#13]
Hi!

Is it possible to set the temperature of the heating hot water?

On the ariston-net.remothermo website it appears in option 6.3.0.0 - Tset Z1

I am not able to find how to do it.

I am running on a CHAFFOTEAUX PIGMA GREEN boiler with the Ariston Sensys control unit, and works well your integration.

Thank you very much for this integration.
![CH](https://user-images.githubusercontent.com/60411863/104490788-9a4a0480-55d1-11eb-88c9-3068c3fbc197.jpg)

**Comment by chomupashchuk** [comment]
Supported items depend on a model and so far I have not seen such a parameter (I got to check only few boilers).
Analyzer can be used to check the request (I use fiddler and chrome browser) but I suspect that it is parameter with name "U6_3_0_0". Since unsupported 1 parameter crashes request some logic should be considered to filter parameter out to not crash other boilers.

If I'll have free time maybe I can prepare a prototype with new parameter for you to test.

**Comment by HassioAwi** [comment]
Thanks a lot!

If you need acces to my remotethermo, just tell me and i will create a password for you.

**Comment by chomupashchuk** [comment]
You may replace files from attached archive, restart HA and then add sensor "ch_water_temperature":
[ariston.zip](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/files/5815761/ariston.zip)
Changing via service requires use of "ch_water_temperature" parameter.

Please let me know if it works. Sharing login credentials might be required if nothing works.

**Comment by HassioAwi** [comment]
Now I can see the water temperature, but I cannot change the value (or I don't know how to do it. I am very newbie).

If you need the credentials, please contact me.
![Temps](https://user-images.githubusercontent.com/60411863/104653785-6e0ab280-56bb-11eb-9313-f9224ad84b11.jpg)

**Comment by chomupashchuk** [comment]
I can contact you after work.
Meanwhile you may try service "ariston.set_data" under Developer Tools - Services
With data:
'''
entity_id: climate.ariston # name of entity
ch_water_temperature: 80 # temperature
'''

**Comment by chomupashchuk** [comment]
You may try the new version uploaded.

**Comment by HassioAwi** [comment]
Fantastic!

Now everything works correctly.

Thank you so much for everything!
