### ISSUE TITLE
ch_set_temperature always reporting same value than ch_comfort_temperature

### ISSUE THREAD

**Issue by facuzestoa** [chomupashchuk/ariston-remotethermo-home-assistant-v2#17]
Hi:
I just noticed that ch_set_temperature it is always reporting ch_comfort_temperature value.
My boiler has a schedule programmed that sets confort temp early in the morning then at 9 goes to economy until sunset when again sets confort until midnight. 
Integration is always reporting confort value (ch_comfort_temperature ) in ch_set_temperature.
Thanks for your support and congrats for your integration!
FYI my boiler is an Ariston Genus One System 35 with a Ariston Sensys Net Bridge/Thermostat. 
Here below my config.yaml for integration

ariston:
    username: xxxxxxxx
    password: xxxxxxx
    name: Caldera
    logging: ERROR
    polling: 1.2
    switches:
        - internet_time
    sensors:
        - account_ch_gas
        - ch_detected_temperature
        - ch_mode
        - ch_comfort_temperature
        - ch_economy_temperature
        - ch_set_temperature
        - ch_water_temperature
        - errors_count
        - heating_last_24h
        - heating_last_30d
        - mode
        - outside_temperature
    binary_sensors:
        - ch_flame
        - flame
        - online

**Comment by chomupashchuk** [comment]
Please try the latest version (1.0.35 or later) and let me know if it works.

**Comment by facuzestoa** [comment]
Hi Oleh
Version 1.0.35 solved the issue, It's working fine now ! 
Thanks
