### ISSUE TITLE
ariston integration not found

### ISSUE THREAD

**Issue by AKRbuilds** [chomupashchuk/ariston-remotethermo-home-assistant-v2#20]
Hi there

My ariston integration got broken.

I've reinstalled it properly but now i'm always getting "component error : Integration 'ariston' not found"
I've reinstalled many time and properly deleted and re-copied folder but nothing worked.

More strange is that i have it install and updated on another HA instance and it works flawlessly.

Any idea? 
Thanks in advance

**Comment by chomupashchuk** [comment]
I can only suggest to check for errors in the log and double check yaml configuration.

**Comment by AKRbuilds** [comment]
thanks! I could fix the problem :)
In the log i found an error which was saying "manifest.json" has a problem
I tried open it and it was corrupted for some reason, i replaced it with a fresh one and the problem was solved.

I'll check the log before posting next time.
Thanks
