### ISSUE TITLE
Confort function Acm

### ISSUE THREAD

**Issue by pantileionut** [chomupashchuk/ariston-remotethermo-home-assistant-v2#21]
possibility of activating / deactivating / timing the comfort function acm alteas one through a switch from home assistant

**Comment by chomupashchuk** [comment]
Do you mean dhw_comfort_function? If so, I can see that it has 3 values, not just ON and OFF. Timing and selection of actions can be part of HA automation process, so I try to avoid complicating the integration with things if same can be easily achieved in HA by means of templates and automation.

**Comment by chomupashchuk** [comment]
DHW Comfort function is controlled through new `select` entity, which was recently introduced in HA. Any timing should be controlled by HA automations.

**Comment by pantileionut** [comment]
it's perfect thank you very much !
