### ISSUE TITLE
Genus One Hybrid Net

### ISSUE THREAD

**Issue by elbowz** [chomupashchuk/ariston-remotethermo-home-assistant-v2#22]
Hello, and thanks for your project!

I should buy the product in subject (a Genus One + Heat pump), do you know if is there support for this?

Anyway, I see that the "simple" Genus One has marked with "Works with HomeKit", so I'm wondering if it also works with HA [HomeKit Controller](https://www.home-assistant.io/integrations/homekit_controller/)?

Thx

**Comment by chomupashchuk** [comment]
Unfortunately I have no idea on what is supported on what hardware. Integration was written for my boiler and adapted in time to work for other people, but I only got temporary access to software configuration part rather than got to know hardware more.

**Comment by elbowz** [comment]
I understand, this is the beatifull of personal project and open source :)

Do you have made some test with HA HomKit Controller...if it works could I have a subset of sensors/control ...or maybe could be used as fallbacks thanks to local push (opposite to cloud poll)...if I haven't missunderstood.

Thanks a lot for your answer...and again for your project and share with others.

**Comment by chomupashchuk** [comment]
I have no apple accessories and no HomeKit to answer how it works or if it works. I connected my Ariston gateway to Google Home, but there was no easy way to automate actions, so the integration was created, which simulates web browser to control boiler via Ariston web server to have more freedom from HA. I was not involved in anything outside that.

Such questions should be asked on the forum, maybe someone tried something.

**Comment by elbowz** [comment]
I'll try to make some research...also on forum.

Anyway, do you suggest your Ariston boiler at the end? by a domotic and also general point of view

p.s. about HomeKit controller, I also don't have Apple stuff, but (always if I have well understood) it's totally indipendent, HA use the HomeKit "protocol" to comunicate with compatible device locally (without Cloud).
Never test because I don't have Apple devices :) 

Thanks again...feel free to close issue
