### ISSUE TITLE
Entity not listed for energy monitor consumption

### ISSUE THREAD

**Issue by apprentice10** [chomupashchuk/ariston-remotethermo-home-assistant-v2#26]
Hello! I'm trying to add the energy consumption for my boiler on the new energy monitor of home assistant, but it's not listed.
Is there any instructions I can follow?

**Comment by chomupashchuk** [comment]
Only sensors `water_today`, `heating_today`, `cooling_today` can support energy consumption. They must be specified in the list of sensors in configuration.yaml.
Another prerequisite is that HA recorder must not exclude sensors (in case you customize it). 
Only after sensor becomes available (successful fetching of all needed data from Ariston server) there should be enough data to make it visible in energy consumption.

At least those are the ones I've encountered. The rest you may ask on HA community forum. My boiler does not support it (always reports 0), so I do not use it myself, i've just checked that energy consumption lists the sensor in latest HA version.
