### ISSUE TITLE
Zone Set Temperature

### ISSUE THREAD

**Issue by IlSaCCo** [chomupashchuk/ariston-remotethermo-home-assistant-v2#29]
Ciao everybody, thanks for the lovely integration,
it is working great on my Ariston Nimbus Compact S Net. 

I was wondering if the reading [and setting] of the CH water temperature at the outlet for each zone can be added to the Integration:
My heatpump has 3 different zone, the aristonnet website is making this call to get the temperatures, here is an example to get zone 1
_https://www.ariston-net.remotethermo.com/Menu/User/Refresh/ZZZZZZZ?paramIds=U6_3_0_0&umsys=si&rnd=XXXXX&_=YYYYYYYY_

To update the value the website is making a POST with this payload:
_[{"id":"U6_3_0_0","newValue":35,"oldValue":33}]_

This would be extremely helpful for users that have heatpump based heating where you do not want to turn off the heatpump but finetune the temperature. Happy to share the CURL that are made if it can be helpful

Cheers

**Comment by chomupashchuk** [comment]
Did you try including "ch_water_temperature" in the sensor list?

**Comment by chomupashchuk** [comment]
Setting of many parameters is described in ariston service to be used as well.

**Comment by IlSaCCo** [comment]
It works like a charm! Apologies I did not see that parameters.
Thanks for the help and for the great project!
