### ISSUE TITLE
Problems to set heating temperature to climate.ariston

### ISSUE THREAD

**Issue by simille83** [chomupashchuk/ariston-remotethermo-home-assistant-v2#3]
Hi, 

When i change the target temperature for heating on climate in Home Assisstant is not set on sensys. the other available functions are set correctly. 
Do you have any idea what the problem could be?

Regards.
Simone

**Comment by chomupashchuk** [comment]
Hi,

Please try using www.ariston-net.remotethermo.com to see if it works. Integration somewhat emulates browser behavior.
One of the reasons some commands did not work in the past was not defined sensors within configuration.yaml, but temperatures should work.
If change of temperatures works via website then please set store_files to true in configuration.yaml, which shall generate multiple files within config folder, which might be used for troubleshooting.

I have very little free time lately, so i can't guarantee anything soon.

**Comment by simille83** [comment]
ariston:
   username: xxxxxxx
   password: xxxxxxx
   store_config_files: true

Is the correct syntax to enter in configuration.yaml? I tried this but the component no longer works afert HA restart.
On www.ariston-net.remotethermo.com the temperature change is it work.
the thing I don't understand is the fact that changing the temperature from HA of the sanitary works, while that of the heating does not.

Thanks for your work.
Simone

**Comment by chomupashchuk** [comment]
store_config_files is on same level in yaml as username/password, so should work.

Changing of temperatures was designed based on 2 boilers (it is reverse engineering, so a lot is my guessing and testing), but even then there were some differences. Please try changing manual/program modes and see if at least in one case change of temperature works.
What kind of boiler do you use? Is the problem with both DHW and CH?

**Comment by chomupashchuk** [comment]
by the way, did you try

**Comment by chomupashchuk** [comment]
No reply for a long time
