### ISSUE TITLE
Set heater water temperature

### ISSUE THREAD

**Issue by costafrancesco94** [chomupashchuk/ariston-remotethermo-home-assistant-v2#30]
Hello :)

I found your work amazing

I saw there is no sensor/option to read the water temperature for heater. There is with domestic hot water, but miss for the heater.

I own a Ariston ClassOneL30, connected with CubeSNet

I set the heater to ignore smart thermostat becouse I already have a thermostat for room, cabled on valves. Connecting as default the CubeSNet it would ignore thermostat and only use the smart one.

I don't know very much of home assistant so I'm not sure about which entity should be added, if there is a schema with "thermnostat" or something, or maybe we could create another "thermostat" entity that does manage the water temperature (we can see from Ariston web page the actual temperature, and the sat one)

I could prepare a PR if guided on which file may have some sample to see how it's working, i'm not very experted in python though...

**Comment by ovimano** [comment]
Hello!
I have an Ariston Alteas One Net. The water heater entity in Home Assistant is water_heater.aaon . AAON is the name I've set in configuration.yaml file here:
  username: !secret ariston_username
  password: !secret ariston_password
  name: **'AAON'** #friendly name for integration, default is Ariston

The climate entity is climate.aaon.

The card I use in Lovelace for water heater is: 
type: custom:water-heater-card
entity: water_heater.aaon

You can find the custom water-heater-card here: https://github.com/rsnodgrass/water-heater-card.
You can find this custom card in HACS as Water Heater Card in Frontend section.

I hope the information is helpful!
