### ISSUE TITLE
Some sensors are unavailable

### ISSUE THREAD

**Issue by VoyteckPL** [chomupashchuk/ariston-remotethermo-home-assistant-v2#31]
![IMG_20220314_180311](https://user-images.githubusercontent.com/10666159/158231319-1ffaafc7-39bf-4017-9032-fd2e396e095e.jpg)
![IMG_20220314_180331](https://user-images.githubusercontent.com/10666159/158231330-1e0d65bf-ea84-4d03-9ab4-d6b183d0f699.jpg)
Some sensors are unavailable.
Ariston genus one with bch.

**Comment by itmcompl** [comment]
I have the similar situation :(

**Comment by chomupashchuk** [comment]
Due to war in my country I do not plan to invest my time in this for now

**Comment by VoyteckPL** [comment]
Stay safe!

**Comment by doctorvanmartin** [comment]
>  Some sensors are unavailable. Ariston genus one with bch.

Happy to help from here, but you need to describe a little bit more your problem. I'm using the integration with no problems at all, and it's code hasn't change since December 2021. So maybe your problem is only on your side or maybe caused by a disruption in the Ariston servers. 
Try to check restarting your server and also checking the webpage/app of Ariston.

**Comment by VoyteckPL** [comment]
Hi! Thanks for your support! I'm currently investigating by adding sensor by sensor in ariston.yaml file. So far I found that:

sensor.ariston_dhw_time_program

is causing this error:

<custom_components.ariston.ariston.AristonHandler object at 0x7faee9f6a0> _get_dhw Problem reading data: HTTPSConnectionPool(host='www.ariston-net.remotethermo.com', port=443): Read timed out. (read timeout=10.0)

ch_fixed_temperature:

is causing this error:

<custom_components.ariston.ariston.AristonHandler object at 0x7f9d6cb880> Unsupported sensors detected: {'ch_fixed_temperature'}, disable corresponding binary_sensors/sensors/switches in the configuration

**Comment by doctorvanmartin** [comment]
First of all have in mind what the documentation says: 
https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2#selectors

-> Some parameters are not supported on all models

And then look for them in the ariston web page, if the web page do not show this information it will likely not be available. Also instead of trying to have them all, only retrive what you like to display or interact with

> sensor.ariston_dhw_time_program
> is causing this error:
> <custom_components.ariston.ariston.AristonHandler object at 0x7faee9f6a0> _get_dhw Problem reading data: HTTPSConnectionPool(host='www.ariston-net.remotethermo.com', port=443): Read timed out. (read timeout=10.0)

I didn't found this one on the listed sensors

 
> ch_fixed_temperature:
> is causing this error:
> <custom_components.ariston.ariston.AristonHandler object at 0x7f9d6cb880> Unsupported sensors detected: {'ch_fixed_temperature'}, disable corresponding binary_sensors/sensors/switches in the configuration

Looks like it is unsupported by your system.

**Comment by doctorvanmartin** [comment]
Sorry, 'sensor.ariston_dhw_time_program' will be 'ch_program' on the configuration yaml. Maybe you don't have any schedules setted.

**Comment by VoyteckPL** [comment]
These sensors were available on my system. My motherboard was replaced and now I have this problem. 
ch_fixed_temperature used to work on my system as well.

**Comment by VoyteckPL** [comment]
dhw_time_program - I have programs schedules for DHW set. But this is not so important, it is just for viewing. The problem is that ch_fixed_temperature is not available, I think ariston might remove those settings. Not sure yet. I used this option quite a lot.

**Comment by doctorvanmartin** [comment]
> These sensors were available on my system. My motherboard was replaced and now I have this problem. ch_fixed_temperature used to work on my system as well.

Is the gateway number the same? Do you have only one listed on https://www.ariston-net.remotethermo.com/ under manage appliances? 

You could also try to change the name of the integration and specify the gateway number manually, like here:

ariston:
  - name: new_name
    gw: "GAETWAYNUMBER"  # The ending of the URL https://www.ariston-net.remotethermo.com/.../[GAETWAYNUMBER]
    username: !secret ariston_username
    password: !secret ariston_password
    ...

**Comment by VoyteckPL** [comment]
Yes, the gateway number didn't change. I have only one listed. I added it like you said as well.

**Comment by doctorvanmartin** [comment]
> The problem is that ch_fixed_temperature is not available, I think ariston might remove those settings. Not sure yet. I used this option quite a lot.

I don't use that sensor, but looking at the code is on the menu, at position 6.3.0.1. Check it on the Ariston web, if it is still there.

**Comment by VoyteckPL** [comment]
![image](https://user-images.githubusercontent.com/10666159/158385569-4ab3acb6-fabd-41e1-98b5-6d28155afe7c.png)
Looks like it was removed...

**Comment by doctorvanmartin** [comment]
>  Looks like it was removed...

Somehow moved I will say, for me stays on 'position'. Looks like its a change for your type of boiler from Ariston:
![imagen](https://user-images.githubusercontent.com/57418570/158390435-9301d93d-7c5b-4c93-8f56-e22f545b53f3.png)

You could try to change the menu value just for your installation by changing the line 380 of the file ariston.py that will be located on your config directory config/custom_components/ariston/ariston.py:
from
   _ARISTON_CH_FIXED_TEMP = "U6_3_0_1"
to
   _ARISTON_CH_FIXED_TEMP = "U6_3_0_0"

**Comment by VoyteckPL** [comment]
Thanks. I think this is not this parameter. I'm talking about heating curve shift which can be moved from -7C to +7C.

**Comment by doctorvanmartin** [comment]
> Thanks. I think this is not this parameter. I'm talking about heating curve shift which can be moved from -7C to +7C.

In my installation the parameter "U6_3_0_1" showed on the menu does what you said, moving from -7C to +7C. But I have the menu elements 1,3 & 5 and you 0, 2 & 4, that seems to have different values. I don't have any documentation from Ariston on those items.

If you don't have it on the Ariston Web page menu, or has a different function, seems like you are not going to have it using this integration (as it only takes the value from the web) :( .

**Comment by VoyteckPL** [comment]
Looks like it is fixed now. I suppose ariston made some changes. I have now option 6 3 0 1 and it works in range from -7 to 7. Maybe motherboard replacemnt affected it, not sure. Anyway, thanks a lot for your support.
