### ISSUE TITLE
zone 1 not present

### ISSUE THREAD

**Issue by danygi79** [chomupashchuk/ariston-remotethermo-home-assistant-v2#32]
Hi, i am using this integration successfully, and thank you for the work done. 
I can clearly see the water pressure and the status of the heat pump, but in no way can I set the temperature of zone 1. 
No sensor and no set appear for this.

thanks
  Daniele

**Comment by ovimano** [comment]
Hello, Daniele!
Did you setup the zone on Ariston web application([https://www.ariston-net.remotethermo.com/])?

At the begining i've been stuck on the same problem.
Thank you!
Ovidiu

**Comment by danygi79** [comment]
Hello,
In my model Zone 1 is necessary to manage the shift of the climatic curve, not a real temperature set..
The setting is correct on the site and from there it works correctly, but from this integration it is not displayed.

**Comment by chomupashchuk** [comment]
There can be different reasons for integration not showing things:
- incorrect integration selected (probably not your case as aristonaqua probably has no zone heatings and DHW requests are different)
- correct integration but some missing data from REST request returned from the website, which crashes the processing
- 
Without more precise data I can't say anything for sure

**Comment by chomupashchuk** [comment]
Api changed and no info provided
