### ISSUE TITLE
Connection problem Chaffoteaux link

### ISSUE THREAD

**Issue by ernesto-dot** [chomupashchuk/ariston-remotethermo-home-assistant-v2#33]
Hi all,
first of all  thank you for the work done....
I'm trying to configure component in HA for my Chffoteaux Chaffolink heating.
It should be work since I'm able to connect and login into https://www.ariston-net.remotethermo.com/.
But I receivede the following problem:

ariston action nok for _get_main: Login parsing of URL failed
13:00:23 – (AVVISO) Ariston (integrazione personalizzata) - il messaggio si è verificato per la prima volta alle 12:57:53 e compare 6 volte
Connection errors: 2
13:00:23 – (AVVISO) Ariston (integrazione personalizzata) - il messaggio si è verificato per la prima volta alle 12:57:53 e compare 6 volte
<custom_components.ariston.ariston.AristonHandler object at 0x7f62b57ee0> Authentication login error
13:00:23 – (AVVISO) Ariston (integrazione personalizzata) - il messaggio si è verificato per la prima volta alle 12:57:53 e compare 6 volte

Have you some idea about ?
Thanks in advance

**Comment by hellcatmon** [comment]
Have the same issue, something goes wrong during login process.

The same error log with boiler Genus One

**Comment by hellcatmon** [comment]
Thanks for a quick fix. Works fine right now. 

@ernesto-dot  pick the last release 1.0.52

**Comment by pico1881** [comment]
Thank you  for the fix, this integration Is very important for mi HA automation

**Comment by bazantos** [comment]
Thank you for update

**Comment by ernesto-dot** [comment]
Thank you for the fix, this integration Is very important for mi HA automation
