### ISSUE TITLE
Total energy is doubled on Energy Dashboard

### ISSUE THREAD

**Issue by dcro** [chomupashchuk/ariston-remotethermo-home-assistant-v2#34]
I noticed an error with the total heating and DHW energy totals in the energy dashboard. Most of the time the values show up correctly but from time to time the total energy spikes up in the Energy Dashboard, almost doubling the total energy for the day, although the sensors do show the correct values.

In the screenshots below, the total for 24 hours and the total for today match the values from the RemoteThermo site, but the energy total shows a spike at 16:00 when the entire quantity for the day was doubled (around 50KW more added). I've also included the values graph for the 24 hours and total today sensors so you get a better idea.

This might be related to issue #25 but it's not exactly the same as the sensors don't pass through a zero value when this issue appears.

<img width="1346" alt="Screen Shot 2022-04-04 at 22 09 47" src="https://user-images.githubusercontent.com/1079773/161614833-24211240-8770-44b7-b850-0f8dad3000f0.png">

<img width="1357" alt="Screen Shot 2022-04-04 at 22 09 13" src="https://user-images.githubusercontent.com/1079773/161614726-c8dd6602-8d1d-4541-b3c0-4ee5aa7764b2.png">

<img width="1054" alt="Screen Shot 2022-04-04 at 22 02 11" src="https://user-images.githubusercontent.com/1079773/161613591-74baa9ad-6ebf-44cb-8908-2a465eacfde7.png">

<img width="386" alt="Screen Shot 2022-04-04 at 22 04 11" src="https://user-images.githubusercontent.com/1079773/161613907-6345ca23-69b6-4e2b-b50b-ae62d5fd5f86.png">

<img width="389" alt="Screen Shot 2022-04-04 at 22 04 55" src="https://user-images.githubusercontent.com/1079773/161614014-be3b1458-c7f3-40f5-8b84-e619352cf505.png">

**Comment by chomupashchuk** [comment]
My boiler does not step values for the sensor and it simply sums up values for hours that represent today. The only way is to put traces or traps.
You may add
```
self._LOGGER.warning(f"ENERGY DATA: {self._ariston_gas_data}")
```
on line 1995 (before for today_sensor in self._TODAY_SENSORS:). It would log each processed data and then when you encounter the issue, you need to check corresponding value in the log (ENERGY DATA shall be in the entry). You probably would need to open full log rather than use shortened web version.

**Comment by chomupashchuk** [comment]
No action plus change of api
