### ISSUE TITLE
Energy values

### ISSUE THREAD

**Issue by Gabyyh** [chomupashchuk/ariston-remotethermo-home-assistant-v2#39]
I always update the newset version, but util jul 11 i havent data from any energy entitiy.
I try to remove the all ariston component and reinstall again, but not success.

**Comment by chomupashchuk** [comment]
Values depend on a model. My boiler always report 0 for everything, but it works for those who can see graphs in Android or Web page.
Can you clarify the issue as I do not understand.

**Comment by Gabyyh** [comment]
it has worked flawlessly so far, I also saw the daily, monthly, weekly and yearly data.

**Comment by Gabyyh** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/35803311/179970766-d88c73e5-da2b-4283-bda4-8c252ed7d0cd.png">

<img width="889" alt="image" src="https://user-images.githubusercontent.com/35803311/179971815-5e429591-7e21-4814-84a2-de73e539db7e.png">

**Comment by chomupashchuk** [comment]
Did you specify new sensors from Readme?

**Comment by Gabyyh** [comment]
Sure. This is my config file:
ariston:
  username: !secret
  password: !secret
  sensors:
    - ch_detected_temperature
    - ch_mode
    - ch_comfort_temperature
    - ch_economy_temperature
    - ch_set_temperature
    - dhw_set_temperature
    - errors_count
    - mode
    - outside_temperature
    - dhw_storage_temperature
    - ch_flow_temperature
    - outside_temperature
    - ch_gas_last_month
    - ch_electricity_last_month
    - dhw_gas_last_month
    - dhw_electricity_last_month
    - pressure
    - ch_energy_today
    - ch_energy_yesterday
    - dhw_energy_today
    - dhw_energy_yesterday
    - ch_energy_this_week
    - ch_energy_last_week
    - dhw_energy_this_week
    - dhw_energy_last_week
    - ch_energy_this_month
    - ch_energy_last_month
    - dhw_energy_this_month
    - dhw_energy_last_month
    - ch_energy_this_year
    - ch_energy_last_year
    - dhw_energy_this_year
    - dhw_energy_last_year
    - integration_version
  binary_sensors:
    - changing_data
    - online
    - flame
    - ch_flame

**Comment by Gabyyh** [comment]
I was try [this](https://github.com/fustom/ariston-remotethermo-home-assistant-v3) on other HA, but this dont work too. Everything work, just the energy dont.

I use your code for a long time and it work perfectly before jul 11.

**Comment by chomupashchuk** [comment]
On Jun 11 Ariston stopped supporting old requests and it forces switching to new ones. This is reverse engineering of requests and my boiler is limited in functionality.
You may add after line 1103 (after self._energy_use_data = copy.deepcopy(resp.json())) in ariston.py
```
self._LOGGER.warn(f'{self._energy_use_data}')
```
it should log reply data.
All I get is following data and so far for Genus One it looks like k=1 was CH and k=2 for DHW. I have no idea if it is different for your boiler.
The dete looks something like 
```
[{"k":7,"p":1,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":7,"p":2,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":7,"p":3,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":7,"p":4,"v":[0.0,0.0,0.0,0.0,0.0,33.444,0.0,6.294,149.963,547.13,777.894,461.645,1014.125,840.43,0.0,720.102,214.919,0.0]},{"k":20,"p":1,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":20,"p":2,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":20,"p":3,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":20,"p":4,"v":[0.0,0.0,0.0,0.0,0.0,0.491,0.0,0.038,2.166,7.838,10.53,5.931,14.633,12.202,0.0,9.219,2.694,0.0]},{"k":10,"p":1,"v":[0.0,1.858,0.0,0.0,0.0,0.0,0.0,2.45,0.0,0.0,1.802,0.0,0.0,3.577,0.0,0.0,0.0,0.0,1.825,0.0,1.763,0.0,0.0,1.191]},{"k":10,"p":2,"v":[5.844,9.391,7.677,8.311,6.016,8.161,7.83]},{"k":10,"p":3,"v":[6.488,10.269,7.372,8.733,7.527,8.194,6.505,7.991,5.697,7.4,9.622,8.3,7.841,12.788,6.158,5.569,3.069,4.986,12.644,5.652,11.5,7.722,8.705,7.894,7.713,5.355,7.638,6.802,9.016,7.991,10.702,11.347,5.43,5.28,7.105,5.986,5.55,7.244,12.2,7.825,5.844,9.391,7.677,8.311,6.016,8.161,7.83]},{"k":10,"p":4,"v":[0.0,0.0,0.0,0.0,0.0,235.675,231.927,281.088,110.236,236.219,282.322,112.271,326.758,291.052,0.0,256.005,294.913,233.155]},{"k":21,"p":1,"v":[0.0,0.011,0.0,0.0,0.0,0.0,0.0,0.011,0.0,0.0,0.011,0.0,0.0,0.019,0.0,0.0,0.0,0.0,0.011,0.0,0.011,0.0,0.0,0.005]},{"k":21,"p":2,"v":[0.036,0.052,0.047,0.047,0.036,0.047,0.041]},{"k":21,"p":3,"v":[0.036,0.05,0.044,0.047,0.041,0.047,0.036,0.047,0.033,0.044,0.052,0.044,0.047,0.066,0.036,0.033,0.019,0.027,0.069,0.033,0.061,0.044,0.047,0.047,0.044,0.03,0.044,0.038,0.05,0.044,0.058,0.063,0.03,0.033,0.041,0.033,0.036,0.041,0.066,0.047,0.036,0.052,0.047,0.047,0.036,0.047,0.041]},{"k":21,"p":4,"v":[0.0,0.0,0.0,0.0,0.0,1.372,1.361,1.641,0.627,1.33,1.544,0.606,1.75,1.552,0.0,1.383,1.597,1.311]},{"k":1,"p":1,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":1,"p":2,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":1,"p":3,"v":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]},{"k":1,"p":4,"v":[0.0,0.0,0.0,0.0,0.0,33.935,0.0,6.332,152.129,554.968,788.424,467.576,1028.758,852.632,0.0,729.321,217.613,0.0]},{"k":2,"p":1,"v":[0.0,1.869,0.0,0.0,0.0,0.0,0.0,2.461,0.0,0.0,1.813,0.0,0.0,3.596,0.0,0.0,0.0,0.0,1.836,0.0,1.774,0.0,0.0,1.196]},{"k":2,"p":2,"v":[5.880,9.443,7.724,8.358,6.052,8.208,7.871]},{"k":2,"p":3,"v":[6.524,10.319,7.416,8.780,7.568,8.241,6.541,8.038,5.730,7.444,9.674,8.344,7.888,12.854,6.194,5.602,3.088,5.013,12.713,5.685,11.561,7.766,8.752,7.941,7.757,5.385,7.682,6.840,9.066,8.035,10.760,11.410,5.46,5.313,7.146,6.019,5.586,7.285,12.266,7.872,5.880,9.443,7.724,8.358,6.052,8.208,7.871]},{"k":2,"p":4,"v":[0.0,0.0,0.0,0.0,0.0,237.047,233.288,282.729,110.863,237.549,283.866,112.877,328.508,292.604,0.0,257.388,296.510,234.466]}]
```
You'd need to check which "k" might correspond to values displayed in Android/IOS or Webpage.
I have all values as "0" in my boiler so I have no idea what means what.

**Comment by chomupashchuk** [comment]
You would need to restart HA after updating file. It should log reply as warning

**Comment by Gabyyh** [comment]
I put it. Where can i find the data?

**Comment by Gabyyh** [comment]
something went wrong:
Logger: homeassistant.loader
Source: custom_components/ariston/__init__.py:24 
Integration: ariston ([documentation](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2), [issues](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/issues)) 
First occurred: 14:40:18 (1 occurrences) 
Last logged: 14:40:18

Unexpected exception importing component custom_components.ariston
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ariston/__init__.py", line 24, in <module>
    from .ariston import AristonHandler
  File "/config/custom_components/ariston/ariston.py", line 1104
    	    self._LOGGER.warn(f'{self._energy_use_data}')
    ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by chomupashchuk** [comment]
it means indentation is incorrect, expected. Also try use spaces prior to `self._LOGGER` as tabs could have been used:
```

        elif request_type == self._REQUEST_ENERGY:

            self._energy_use_data = copy.deepcopy(resp.json())
            self._LOGGER.warn(f'{self._energy_use_data}')
            this_month = datetime.date.today().month
            this_year = datetime.date.today().year
            this_day = datetime.date.today().day
            this_day_week = datetime.date.today().weekday()
            this_hour = datetime.datetime.now().hour
```
By the way, do you have electric or gas boiler? - current sensors seem to work for gas on Genus One.

**Comment by Gabyyh** [comment]
I will try it.
I have Ariston Premium Evo System gas

**Comment by Gabyyh** [comment]
ok, i put it to the code.

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 1378, in run
    self.function(*self.args, **self.kwargs)
  File "/config/custom_components/ariston/ariston.py", line 1461, in _queue_get_data
    last_index_low_prio = self._requests_lists[1].index(self._last_request_low_prio)
ValueError: 'ch_schedule' is not in list

**Comment by Gabyyh** [comment]
where find the value what we loking? in the log its nothing

**Comment by chomupashchuk** [comment]
there seems to be an issue with queue mechanism. I'll send here file with a fix to try out

**Comment by chomupashchuk** [comment]
[ariston.py.txt](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/files/9151663/ariston.py.txt)
remove trailing `.txt` and replace the file (GitHub does not allow `.py` files)

**Comment by Gabyyh** [comment]
thanks, i replace it
where find the log what you need?

**Comment by chomupashchuk** [comment]
it should take few minutes to gather data and get to energy fetching. After this you may check sensors if they work now (in case exception caused it), and in Settings->System->Logs there should be entry that starts with `ENERGY USE DATA:` in case problem still persists

**Comment by Gabyyh** [comment]
ENERGY USE DATA: [{'k': 7, 'p': 1, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 7, 'p': 2, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 7, 'p': 3, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 7, 'p': 4, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 51.308, 472.283, 738.513, 378.184, 1085.822, 747.8, 771.972, 489.45, 30.175, 0.0]}, {'k': 20, 'p': 1, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 20, 'p': 2, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 20, 'p': 3, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 20, 'p': 4, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.65, 5.994, 9.375, 4.801, 13.783, 9.491, 9.8, 6.211, 0.38, 0.0]}, {'k': 10, 'p': 1, 'v': [1.8, 2.527, 0.0, 0.0, 0.0, 0.0, 0.0, 1.766, 0.0, 0.0, 0.0, 1.711, 0.0, 0.0, 2.283, 0.0, 0.0, 0.0, 1.766, 0.0, 0.0, 0.0, 1.855, 0.0]}, {'k': 10, 'p': 2, 'v': [7.875, 6.525, 6.175, 9.08, 4.438, 9.563, 5.761]}, {'k': 10, 'p': 3, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.216, 6.022, 8.808, 14.197, 6.208, 6.438, 7.005, 6.163, 8.652, 6.269, 7.691, 6.227, 3.638, 7.875, 6.525, 6.175, 9.08, 4.438, 9.563, 5.761]}, {'k': 10, 'p': 4, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 226.497, 271.872, 292.911, 109.101, 284.808, 269.347, 311.75, 284.902, 258.561, 229.35]}, {'k': 21, 'p': 1, 'v': [0.002, 0.005, 0.0, 0.0, 0.0, 0.0, 0.0, 0.002, 0.0, 0.0, 0.0, 0.002, 0.0, 0.0, 0.002, 0.0, 0.0, 0.0, 0.002, 0.0, 0.0, 0.0, 0.002, 0.0]}, {'k': 21, 'p': 2, 'v': [0.016, 0.013, 0.013, 0.019, 0.008, 0.019, 0.011]}, {'k': 21, 'p': 3, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.013, 0.011, 0.019, 0.03, 0.013, 0.013, 0.013, 0.013, 0.019, 0.013, 0.016, 0.013, 0.005, 0.016, 0.013, 0.013, 0.019, 0.008, 0.019, 0.011]}, {'k': 21, 'p': 4, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.511, 0.613, 0.661, 0.246, 0.641, 0.605, 0.702, 0.641, 0.583, 0.516]}, {'k': 1, 'p': 1, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 1, 'p': 2, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 1, 'p': 3, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}, {'k': 1, 'p': 4, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 51.958, 478.277, 747.888, 382.985, 1099.605, 757.291, 781.772, 495.661, 30.555, 0.0]}, {'k': 2, 'p': 1, 'v': [1.802, 2.532, 0.0, 0.0, 0.0, 0.0, 0.0, 1.768, 0.0, 0.0, 0.0, 1.713, 0.0, 0.0, 2.285, 0.0, 0.0, 0.0, 1.768, 0.0, 0.0, 0.0, 1.857, 0.0]}, {'k': 2, 'p': 2, 'v': [7.891, 6.538, 6.188, 9.099, 4.446, 9.582, 5.772]}, {'k': 2, 'p': 3, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.229, 6.033, 8.827, 14.227, 6.221, 6.451, 7.018, 6.176, 8.671, 6.282, 7.707, 6.24, 3.643, 7.891, 6.538, 6.188, 9.099, 4.446, 9.582, 5.772]}, {'k': 2, 'p': 4, 'v': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 227.008, 272.485, 293.572, 109.347, 285.449, 269.952, 312.452, 285.543, 259.144, 229.866]}]

**Comment by chomupashchuk** [comment]
and do sensors provide valid data now?

**Comment by Gabyyh** [comment]
its show data, i try to check they valid

**Comment by Gabyyh** [comment]
I think its not good:
Ariston DHW energy last month 6,216 kWh but in the ariston site it write i used 22m3 (220 kWh) last month

The other look like valid:
Ariston DHW energy today 3,621 kWh, in the site it looks just 0,4m3 (4kWh)
riston DHW energy yesterday 5,76 kWh, in the site it look 0,5m3 (5kWh)

**Comment by chomupashchuk** [comment]
do you have Android or IOS application? The requests are based on Android and the values are in kWh there unlike website.

**Comment by Gabyyh** [comment]
I have IOS, but i check it in the https://www.ariston-net.remotethermo.com website and i know i used 22m3 in last month from the bill:)

**Comment by Gabyyh** [comment]
sorry, i dont see the correct :)
Ariston Gas use for DHW Last Month 230 kWh. its perfect.

But what is the different between sensor.ariston_gas_use_for_dhw_last_month and sensor.ariston_dhw_energy_last_month?
the first is the usage gas quantity, but what is the other, the DHW energy?

**Comment by Gabyyh** [comment]
And my last question:
I have value for the sensor.ariston_dhw_energy_today (3,621 kWh).
But in the energy dashboard it why zero value?
<img width="873" alt="image" src="https://user-images.githubusercontent.com/35803311/180032945-bb991c23-e3c2-41d3-85bc-c4b22929dec3.png">

**Comment by chomupashchuk** [comment]
it's a bit complicated. There is dedicated request, which reports last months total use and inside it has gas and electricity accumulated values.
Another request (from which you attached data from logger) as you see is bunch of numbers from which I try to collect the data for the senors. Seems like last month data calculation is faulty by nature based on received data. I also see flaw in weeks calculation.

I have not used the dashboard myself due to lack of data, so not sure

**Comment by Gabyyh** [comment]
The calculation is good, in the dashboard look valid value, just in the energy dashboard cant see it.
in some version eralier, before jul 11, the energy dashboard was show perfect value. I used this entitiy in: sensor.ariston_energy_use_for_heating_today and sensor.ariston_energy_use_for_water_today

AND thank you for your great work on the integration 🥇

**Comment by chomupashchuk** [comment]
New version is published.
If i remeber correctly, dashboard has delays in update (half an hour or hour) and connected to recorder.
As for last month - it is even more complex. On Genus One (from guy who provided me with access) does have correct values in provided data, but your boiler has part of data for last month as 0 for some reason.

**Comment by Gabyyh** [comment]
Thank you
