### ISSUE TITLE
Heat pump binary sensor not working

### ISSUE THREAD

**Issue by fabiopellegrin** [chomupashchuk/ariston-remotethermo-home-assistant-v2#48]
Hi,
first things: thanks for all your work!

Seems that the binary_sensor.ariston_heat_pump is not working, and shows up as "Not available".
Looking the code seems that the heat pump part is missing.

Thanks in advice,
BR
Fabio

**Comment by chomupashchuk** [comment]
Since requests were changed by Ariston I have not found so far data on how to read heat pump data in my boiler.

**Comment by fabiopellegrin** [comment]
[HeatPumpFix.txt](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/files/9610943/HeatPumpFix.txt)

This patch work for my hybrid system.

**Comment by chomupashchuk** [comment]
included in 2.0.14
