### ISSUE TITLE
Ariston Alteas One Net 35

### ISSUE THREAD

**Issue by ovimano** [chomupashchuk/ariston-remotethermo-home-assistant-v2#5]
Hello!
I have a Ariston Alteas One Net 35 boiler and with the v1(previos version) integration I managed to monitor and control some of the parameters in the boiler. With this version I have some issues:

- climate.aaon is unavailable
- water_heater.aaon is unavailable

but:
- sensor.aaon_account_ch_gas_use
- binary_sensor.aaon_flame
an a lot of the sensors and binary_sensors are available.

I am doing something wrong?

My config is:

  username: !secret ariston_username
  password: !secret ariston_password
  name: 'AAON' #friendly name for integration, default is Ariston
  hvac_off_present: 'true' #indicates if HVAC OFF shall be present in climate entity. Default value is false.
  hvac_off: 'summer' #indicates how to treat HVAC OFF action in climate (use depends on hvac_off_present). Options are off and summer. By default it is summer, which means that turning off would keep DHW water heating on (e.g. summer mode). Presets in climate allow switching between off, summer and winter.
  store_config_files: 'false' #true or false indicating if configuration json files to be stored in /config/custom_components/ariston folder. Can be used for troubleshooting purposes. Default value is false. 
  units: 'metric' #which uniots to be used. Values are: metric (°C-bar-kW...), imperial (°F-psi-kBtu/h...), auto (detect automatically, which takes additional time). Default is metric. Note that use of auto requires additional request to be used, which would result in slower update of other sensors.
  polling: 1.0 #sets floating value of relative polling rate. Default is 1.0. Setting value to 2.0 for example would increase timeouts times and retries by 2 times. It is recommended to set this value to more than one (e.g. 1.2) in case timeouts take place very frequently.
  switches:
    - internet_time #turn off and on sync with internet time.
    - internet_weather #turn off and on fetching of weather from internet.
    - ch_auto_function #turn off and on Auto function.
    - dhw_thermal_cleanse_function #DHW thermal cleanse function enabled.
  sensors:
    - account_ch_gas #- gas use summary for CH. Not supported on all models.
    - account_ch_electricity #- electricity use summary for CH. Not supported on all models.
    - account_dhw_gas #- gas use summary for DHW. Not supported on all models.
    - account_dhw_electricity #- electricity use summary for DHW. Not supported on all models.
    - ch_antifreeze_temperature #- CH antifreeze temperature.
    - ch_detected_temperature #- temperature measured by thermostat.
    - ch_mode #- mode of CH (manual or scheduled and others).
    - ch_comfort_temperature #- CH comfort temperature.
    - ch_economy_temperature #- CH economy temperature.
    - ch_set_temperature #- set CH temperature.
    - ch_program #- CH Time Program.
    - cooling_last_24h #- energy use for pump cooling in a day.
    - cooling_last_7d #- energy use for pump cooling in a week.
    - cooling_last_30d #- energy use for pump cooling in a month.
    - cooling_last_365d #- energy use for pump cooling in a year.
    - dhw_program #- DHW Time Program.
    - dhw_comfort_function #- DHW comfort function.
    - dhw_mode #- mode of DHW. Not supported on all models.
    - dhw_comfort_temperature #- DHW storage comfort temperature. Not supported on all models.
    - dhw_economy_temperature #- DHW storage economy temperature. Not supported on all models.
    - dhw_set_temperature #- set DHW temperature.
    - dhw_storage_temperature #- DHW storage temperature. Not supported on all models.
    - dhw_thermal_cleanse_cycle #- DHW thermal cleanse cycle.
    - electricity_cost #- Electricity cost.
    - errors_count #- active errors (no actual errors to test on).
    - gas_type #- Gas type.
    - gas_cost #- Gas cost.
    - heating_last_24h #- energy use for heating in last 24 hours. Not supported on all models.
    - heating_last_30d #- energy use for heating in last 7 days. Not supported on all models.
    - heating_last_365d #- energy use for heating in last 30 days. Not supported on all models.
    - heating_last_7d #- energy use for heating in last 365 days. Not supported on all models.
    - mode #- mode of boiler (off or summer or winter and others).
    - outside_temperature #- outside temperature. Not supported on all models.
    - signal_strength #- Wifi signal strength.
    - units #- Units of measurement
    - water_last_24h #- energy use for water in last 24 hours. Not supported on all models.
    - water_last_30d #- energy use for water in last 7 days. Not supported on all models.
    - water_last_365d #- energy use for water in last 30 days. Not supported on all models.
    - water_last_7d #- energy use for water in last 365 days. Not supported on all models.
  binary_sensors:
    - ch_auto_function #- CH AUTO function status.
    - ch_flame #- CH heating ongoing.
    - ch_pilot #- CH Pilot mode.
    - dhw_flame #- DHW heating ongoing. This parameter is not reported by boilers and is approximated based on multiple parameters.
    - dhw_thermal_cleanse_function #- DHW thermal cleanse function.
    - flame #- CH and/or DHW heating ongoing.
    - heat_pump #- Heating pump status.
    - holiday_mode #- Holiday mode status.
    - internet_time #- Internet time status.
    - internet_weather #- Internet weather status.
    - changing_data #- API is attempting to configure requested data. API specific sensor.
    - online #- Online status. Indicates if API has communication with the heater. API specific sensor.
    - update #- API update status. API specific sensor.

And my errors in the log file are:

Logger: custom_components.ariston.ariston
Source: custom_components/ariston/ariston.py:1778
Integration: Ariston (documentation)
First occurred: 11:14:42 AM (5 occurrences)
Last logged: 11:26:43 AM

<custom_components.ariston.ariston.AristonHandler object at 0xb142afd0> _get_param invalid reply code 500

Logger: homeassistant.helpers.entity
Source: custom_components/ariston/sensor.py:271
First occurred: 11:15:13 AM (347 occurrences)
Last logged: 11:26:45 AM

Update for sensor.aaon_active_errors fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ariston/sensor.py", line 271, in update
    self._attrs[valid_error] = ""
TypeError: unhashable type: 'dict'

In the mean time, i'll try to change the polling to 2 instead of 1.2.

Thank you for your work!

**Comment by chomupashchuk** [comment]
Try removing/commenting out 'internet_weather' from binary sensors and switches. 
Previous issue on Alteas One was the same "_get_param invalid reply code 500" which was caused by server replying with no support of that specific parameter. Since request is made for multiple parameters at once and many of them are essential for climate and water heater entities that unsuccessful reply causes many parameters being missing.
Information included in README.MD

**Comment by chomupashchuk** [comment]
https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/issues/4
