### ISSUE TITLE
Missing error sensor

### ISSUE THREAD

**Issue by inode-** [chomupashchuk/ariston-remotethermo-home-assistant-v2#6]
Hello,

I was trying your integration an seems to work pretty fine, but I saw a problem on the error management. Currently if I'm not wrong no "errors" sensor has been defined. Only error_count.

From my understanding the "error_count" doesn't identify the number of error, but someting other (maybe the number of pages). Below you can find an example of responde of "/Error/ActiveDataSource/" when an active error is present:

`{"result":[{"Id":"0080E1BXXXXX_1607224668000_-8509677932000XXXXXX","Severity":2,"Timestamp":"12/6/2020 4:17:48 AM","Fault":"Overheat (101)","Device":"Boiler (0, FE, 1)","IsResettable":true,"IconCssClass":"error-icon","Acknowledged":false}],"count":0}`

From the code I saw that the parsing of the error messages is already present in the library, but no sensor has been defined to use the data.

inode

**Comment by chomupashchuk** [comment]
The intention of errors_count was to have a dedicated sensor for the errors and include details of errors in the attributes, where I have a possibility to input more dynamic data (similar to energy use).
But I had no active errors on my boiler since I've started work on the integration, so I had no idea of how the structure of the reply looks like based on: `{"result": [], "count": 0}`. You are the first one who has sent me some data in that area.
I won't be able to fully verify it, only simulate based on your example.

**Comment by ovimano** [comment]
Hello!
The error codes for Ariston boilers are: https://www.boilerguide.co.uk/manufacturers/ariston/error-codes

On my Alteas One Net 35 i have an active error:
<img width="1054" alt="Screenshot 2020-12-07 at 10 05 30" src="https://user-images.githubusercontent.com/8056590/101325051-cf956100-3873-11eb-861c-d434b20555bc.png">
 and it's 3P9 - Schedule service like in the docs above.

Maybe will help.

Thank you!


P.S.

My error from Home Assistant log is:

Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/ariston/sensor.py:271
First occurred: December 6, 2020, 6:11:18 PM (28605 occurrences)
Last logged: 10:08:05 AM

Update for sensor.aaon_active_errors fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ariston/sensor.py", line 271, in update
    self._attrs[valid_error] = ""
TypeError: unhashable type: 'dict'

**Comment by chomupashchuk** [comment]
Please try the latest version and let me know if it works.
Now `errors_count` should show correct number and attributes should include `Error{}_Slogan`, `Error{}_Severity`, `Error{}_Timestamp` for all active errors.

**Comment by ovimano** [comment]
It works!
Thank you for your work!

I've attached the printscreen.
<img width="401" alt="Screenshot 2020-12-07 at 12 32 27" src="https://user-images.githubusercontent.com/8056590/101340447-6f5cea00-3888-11eb-9c66-d08ed1040af1.png">
